server:
  port: 8081

spring:
  application:
    name: ticket-service

#  security:
#    oauth2:
#      resourceserver:
#        jwt:
#          issuer-uri: ${ISSUER_URI:http://localhost:8080}

db-service:
  url: ${DB_SERVICE_URL:http://localhost:8082}

management:
  endpoints:
    web:
      exposure:
        include: prometheus,health,info
  endpoint:
    prometheus:
      enabled: true
  metrics:
    enable:
      all: true
  prometheus:
    metrics:
      export:
        enabled: true
