server:
  port: 8081

spring:
  application:
    name: ticket-service

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080

db-service:
  url: http://localhost:8082
